import type { WiringLayout } from '../types';

export const MOTION_SENSOR_ALARM_LAYOUT: WiringLayout = {
  slug: '8',
  width: 720,
  height: 500,
  elements: [
    {
      id: 'arduino',
      kind: 'arduino-uno',
      label: 'Arduino Uno',
      aliases: ['arduino uno', 'arduino', 'arduino uno r3'],
      x: 20,
      y: 70,
      width: 210,
      height: 360,
      ports: [
        { id: '5v', label: '5V', dx: 210, dy: 78, aliases: ['5v'] },
        { id: '3v3', label: '3.3V', dx: 210, dy: 108, aliases: ['3v3', '33v'] },
        { id: 'gnd', label: 'GND', dx: 210, dy: 138, aliases: ['gnd'] },
        { id: 'd2', label: 'D2', dx: 210, dy: 198, aliases: ['d2'] },
        { id: 'd8', label: 'D8', dx: 210, dy: 228, aliases: ['d8'] },
        { id: 'd9', label: 'D9', dx: 210, dy: 258, aliases: ['d9'] },
        { id: 'd10', label: 'D10', dx: 210, dy: 288, aliases: ['d10'] },
        { id: 'a0', label: 'A0', dx: 210, dy: 328, aliases: ['a0'] },
        { id: 'a1', label: 'A1', dx: 210, dy: 358, aliases: ['a1'] },
      ],
    },
    {
      id: 'breadboard',
      kind: 'breadboard',
      label: 'Breadboard',
      aliases: ['breadboard'],
      x: 268,
      y: 36,
      width: 428,
      height: 428,
      railDomain: 'logic',
      ports: [
        { id: 'plus', label: '+', dx: 36, dy: 28, aliases: ['plusrail', 'pluslogicrail', 'logicrail'] },
        { id: 'minus', label: '−', dx: 36, dy: 58, aliases: ['minusrail', 'gndrail', 'rail'] },
      ],
    },
    {
      id: 'pir',
      kind: 'pir',
      label: 'PIR',
      aliases: ['pir', 'pir motion sensor'],
      x: 300,
      y: 128,
      width: 168,
      height: 92,
      ports: [
        { id: 'vcc', label: 'VCC', dx: 0, dy: 28, aliases: ['vcc'] },
        { id: 'out', label: 'OUT', dx: 0, dy: 52, aliases: ['out'] },
        { id: 'gnd', label: 'GND', dx: 0, dy: 76, aliases: ['gnd'] },
      ],
    },
    {
      id: 'resistor',
      kind: 'resistor',
      label: '220 Ω',
      aliases: ['220 ohm resistor', 'resistor'],
      x: 300,
      y: 246,
      width: 150,
      height: 44,
      ports: [
        { id: 'leg1', label: 'leg 1', dx: 0, dy: 22, aliases: ['leg1'] },
        { id: 'leg2', label: 'leg 2', dx: 150, dy: 22, aliases: ['leg2'] },
      ],
    },
    {
      id: 'led',
      kind: 'led',
      label: 'LED',
      aliases: ['led'],
      x: 490,
      y: 228,
      width: 88,
      height: 80,
      ports: [
        { id: 'anode', label: 'anode', dx: 0, dy: 40, aliases: ['anode'] },
        { id: 'cathode', label: 'cathode', dx: 88, dy: 40, aliases: ['cathode'] },
      ],
    },
    {
      id: 'buzzer',
      kind: 'buzzer',
      label: 'Buzzer',
      aliases: ['buzzer'],
      x: 300,
      y: 328,
      width: 176,
      height: 92,
      ports: [
        { id: 'vcc', label: 'VCC', dx: 0, dy: 28, aliases: ['vcc', 'vccplus', 'plus'] },
        { id: 'sig', label: 'I/O', dx: 0, dy: 52, aliases: ['ios', 'io', 's', 'sig'] },
        { id: 'gnd', label: 'GND', dx: 0, dy: 76, aliases: ['gnd'] },
      ],
    },
  ],
};
