import type { WiringLayout } from '../types';

export const SERVO_PAN_TILT_CAMERA_LAYOUT: WiringLayout = {
  slug: '18',
  width: 1020,
  height: 760,
  elements: [
    {
      id: 'arduino',
      kind: 'arduino-uno',
      label: 'Arduino Uno',
      aliases: ['arduino uno', 'arduino', 'arduino uno r3'],
      x: 20,
      y: 56,
      width: 200,
      height: 400,
      ports: [
        { id: '5v', label: '5V', dx: 200, dy: 72, aliases: ['5v'] },
        { id: '3v3', label: '3.3V', dx: 200, dy: 108, aliases: ['3v3', '33v'] },
        { id: 'gnd', label: 'GND', dx: 200, dy: 144, aliases: ['gnd'] },
        { id: 'd2', label: 'D2', dx: 200, dy: 204, aliases: ['d2'] },
        { id: 'd9', label: 'D9', dx: 200, dy: 248, aliases: ['d9'] },
        { id: 'd10', label: 'D10', dx: 200, dy: 292, aliases: ['d10'] },
        { id: 'a0', label: 'A0', dx: 200, dy: 340, aliases: ['a0'] },
        { id: 'a1', label: 'A1', dx: 200, dy: 384, aliases: ['a1'] },
      ],
    },
    {
      id: 'breadboard',
      kind: 'breadboard',
      label: 'Breadboard',
      aliases: ['breadboard'],
      x: 348,
      y: 44,
      width: 300,
      height: 248,
      ports: [
        { id: 'logic-plus', label: 'Uno 5V', dx: 28, dy: 26, aliases: ['pluslogicrail', 'logicrail'] },
        { id: 'gnd', label: 'GND', dx: 28, dy: 56, aliases: ['minusrail', 'gndrail', 'rail'] },
        { id: 'servo-plus', label: 'PSU 5V', dx: 272, dy: 26, aliases: ['plusservorail', 'servorail'] },
      ],
    },
    {
      id: 'pan',
      kind: 'servo',
      label: 'Pan servo',
      aliases: ['pan servo'],
      x: 740,
      y: 44,
      width: 216,
      height: 150,
      railDomain: 'servo',
      ports: [
        { id: 'vcc', label: 'VCC', dx: 0, dy: 48, aliases: ['vccred', 'vcc', 'red'] },
        { id: 'gnd', label: 'GND', dx: 0, dy: 78, aliases: ['gndbrown', 'gnd', 'brown'] },
        { id: 'sig', label: 'SIG', dx: 0, dy: 108, aliases: ['sigorange', 'sig', 'orange'] },
      ],
    },
    {
      id: 'tilt',
      kind: 'servo',
      label: 'Tilt servo',
      aliases: ['tilt servo'],
      x: 740,
      y: 216,
      width: 216,
      height: 150,
      railDomain: 'servo',
      ports: [
        { id: 'vcc', label: 'VCC', dx: 0, dy: 48, aliases: ['vccred', 'vcc', 'red'] },
        { id: 'gnd', label: 'GND', dx: 0, dy: 78, aliases: ['gndbrown', 'gnd', 'brown'] },
        { id: 'sig', label: 'SIG', dx: 0, dy: 108, aliases: ['sigorange', 'sig', 'orange'] },
      ],
    },
    {
      id: 'joystick',
      kind: 'joystick',
      label: 'Joystick',
      aliases: ['joystick'],
      x: 348,
      y: 480,
      width: 168,
      height: 196,
      ports: [
        { id: '5v', label: '+5V', dx: 0, dy: 44, aliases: ['plus5v', '5v', 'vcc'] },
        { id: 'gnd', label: 'GND', dx: 0, dy: 76, aliases: ['gnd'] },
        { id: 'vrx', label: 'VRx', dx: 0, dy: 108, aliases: ['vrx'] },
        { id: 'vry', label: 'VRy', dx: 0, dy: 140, aliases: ['vry'] },
        { id: 'sw', label: 'SW', dx: 0, dy: 172, aliases: ['sw'] },
      ],
    },
    {
      id: 'psu',
      kind: 'breadboard-psu',
      label: 'Breadboard PSU',
      aliases: ['breadboard psu'],
      x: 740,
      y: 480,
      width: 216,
      height: 96,
      railDomain: 'servo',
      ports: [
        { id: '5v', label: '5V', dx: 0, dy: 32, aliases: ['5v'] },
        { id: 'gnd', label: 'GND', dx: 0, dy: 68, aliases: ['gnd'] },
      ],
    },
  ],
};
