-- Phase 3.7 project-specific walkthroughs for the six authored-BOM projects.
-- Creates public.project_steps and seeds slugs 1, 4, 8, 11, 12, 14.
-- Does not create walkthroughs for the other 16 projects.
-- Does not change is_published. Does not modify public.components or BOM rows.

-- ---------------------------------------------------------------------------
-- project_steps
-- ---------------------------------------------------------------------------

create table public.project_steps (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects (id) on delete cascade,
  sort_order integer not null,
  title text not null,
  description text not null,
  tip text null,
  blocks jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_steps_project_id_sort_order_key unique (project_id, sort_order),
  constraint project_steps_sort_order_check check (sort_order >= 0)
);

create index project_steps_project_id_sort_order_idx
  on public.project_steps (project_id, sort_order);

create trigger project_steps_set_updated_at
before update on public.project_steps
for each row
execute function public.set_updated_at();

comment on table public.project_steps is
  'Authored walkthrough steps for a catalogue project. blocks is the app StepBlock JSON array.';

comment on column public.project_steps.sort_order is
  '0-based step index. Matches user_projects.current_step.';

comment on column public.project_steps.blocks is
  'JSON array of StepBlock objects used by the build screen (text, image imageKey, wiring, connections, code, tip, warning, expected, troubleshooting, components).';

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.project_steps enable row level security;

create policy "Authenticated users can read steps for published projects"
  on public.project_steps for select to authenticated
  using (
    (select auth.uid()) is not null
    and exists (
      select 1
      from public.projects p
      where p.id = project_steps.project_id
        and p.is_published = true
    )
  );

grant select on public.project_steps to authenticated;
revoke all on public.project_steps from anon;

-- ---------------------------------------------------------------------------
-- Learning objectives for the six authored guides only
-- ---------------------------------------------------------------------------

update public.projects
set learning_objectives = array['Read soil moisture, temperature, humidity, and light on one Arduino', 'Build an LDR voltage divider with the BOM resistor', 'Show live plant readings on an I2C OLED']
where slug = '1'
  and is_published = false;

update public.projects
set learning_objectives = array['Wire DHT22 and BMP280 to an ESP32 at 3.3 V', 'Read temperature, humidity, and barometric pressure', 'Print weather data on the Serial Monitor']
where slug = '4'
  and is_published = false;

update public.projects
set learning_objectives = array['Wire a PIR sensor, LED, and active buzzer to an Arduino Uno', 'Detect motion as a digital HIGH on D2', 'Trigger the LED and buzzer together as an alarm']
where slug = '8'
  and is_published = false;

update public.projects
set learning_objectives = array['Identify LED polarity and why a resistor is required', 'Build the LED circuit on a breadboard', 'Upload a blink sketch and change the delay timing']
where slug = '11'
  and is_published = false;

update public.projects
set learning_objectives = array['Wire three LEDs with one current-limiting resistor each', 'Drive red, yellow, and green from D8, D9, and D10', 'Program a traffic-light sequence with delay()']
where slug = '12'
  and is_published = false;

update public.projects
set learning_objectives = array['Build an LDR voltage divider with one BOM resistor', 'Read analogue light on A0', 'Turn the LED on when the reading drops below a threshold']
where slug = '14'
  and is_published = false;

-- ---------------------------------------------------------------------------
-- Seed authored steps
-- ---------------------------------------------------------------------------

insert into public.project_steps (project_id, sort_order, title, description, tip, blocks)
select
  p.id,
  v.sort_order,
  v.title,
  v.description,
  v.tip,
  v.blocks
from (
  values
  ('1', 0, 'Meet your plant monitor', 'You will wire a soil moisture probe, DHT22, and LDR to an Arduino Uno, then show temperature, humidity, soil, and light on the 0.96" OLED. Every part in this guide is on the project BOM.', 'Power the Arduino from USB while you prototype. You do not need a separate battery pack.', $blocks$[{"type":"image","imageKey":"smartPlantMonitor","caption":"Finished plant monitor reference."},{"type":"text","body":"The Arduino reads three kinds of signal: analogue soil moisture on A0, analogue light on A1 from an LDR divider, and digital DHT22 data on D2. The OLED uses the Uno’s I2C pins (A4 = SDA, A5 = SCL) to print those values."},{"type":"components","items":[{"id":"arduino-uno-r3","name":"Arduino Uno R3","illustrationId":"arduino-uno","owned":false,"quantity":1},{"id":"soil-moisture","name":"Soil moisture sensor","illustrationId":"generic-sensor","owned":false,"quantity":1},{"id":"dht22","name":"DHT22","illustrationId":"dht11","owned":false,"quantity":1},{"id":"ldr","name":"LDR","illustrationId":"generic-sensor","owned":false,"quantity":1},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":1},{"id":"oled-096","name":"0.96\" OLED","illustrationId":"oled","owned":false,"quantity":1},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]}]$blocks$::jsonb),
  ('1', 1, 'Lay out the BOM', 'Place the Uno, breadboard, soil moisture module, DHT22, LDR, resistor, OLED, and jumper wires on the desk and match each item before you insert anything.', null, $blocks$[{"type":"text","body":"The single resistor is for the LDR voltage divider — not a DHT22 pull-up. Use a DHT22 module that already includes its data pull-up, which matches this BOM."},{"type":"components","items":[{"id":"arduino-uno-r3","name":"Arduino Uno R3","illustrationId":"arduino-uno","owned":false,"quantity":1},{"id":"soil-moisture","name":"Soil moisture sensor","illustrationId":"generic-sensor","owned":false,"quantity":1},{"id":"dht22","name":"DHT22","illustrationId":"dht11","owned":false,"quantity":1},{"id":"ldr","name":"LDR","illustrationId":"generic-sensor","owned":false,"quantity":1},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":1},{"id":"oled-096","name":"0.96\" OLED","illustrationId":"oled","owned":false,"quantity":1},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]},{"type":"tip","body":"Keep the soil probe dry until the circuit works. Wet soil too early makes debugging harder."}]$blocks$::jsonb),
  ('1', 2, 'Wire the LDR light divider', 'Build a voltage divider so the Arduino can measure light on analogue pin A1. The LDR and the BOM resistor share the A1 node.', null, $blocks$[{"type":"text","body":"GPIO analogue inputs measure voltage, not resistance. An LDR’s resistance falls as light increases. Putting the LDR from 5V to A1 and the resistor from A1 to GND makes a divider: brighter light raises the A1 voltage."},{"type":"connections","summary":"LDR divider on A1","rows":[{"fromComponent":"LDR","fromPin":"leg 1","toComponent":"Arduino Uno","toPin":"5V"},{"fromComponent":"LDR","fromPin":"leg 2","toComponent":"Arduino Uno","toPin":"A1"},{"fromComponent":"Resistor","fromPin":"leg 1","toComponent":"Arduino Uno","toPin":"A1"},{"fromComponent":"Resistor","fromPin":"leg 2","toComponent":"Arduino Uno","toPin":"GND"}]},{"type":"warning","body":"Do not add a second resistor for the DHT22. This project’s only resistor is the LDR divider."}]$blocks$::jsonb),
  ('1', 3, 'Connect the soil probe and DHT22', 'The soil module is analogue on A0. The DHT22 is a digital one-wire sensor on D2. Both share the Uno 5V and GND rails.', null, $blocks$[{"type":"wiring","pair":{"leftName":"Arduino Uno","leftId":"arduino-uno","rightName":"DHT22","rightId":"dht11"},"connections":[{"fromComponent":"DHT22","fromPin":"VCC","toComponent":"Arduino Uno","toPin":"5V"},{"fromComponent":"DHT22","fromPin":"GND","toComponent":"Arduino Uno","toPin":"GND"},{"fromComponent":"DHT22","fromPin":"DATA","toComponent":"Arduino Uno","toPin":"D2"}]},{"type":"connections","summary":"Soil moisture analogue output","rows":[{"fromComponent":"Soil moisture","fromPin":"VCC","toComponent":"Arduino Uno","toPin":"5V"},{"fromComponent":"Soil moisture","fromPin":"GND","toComponent":"Arduino Uno","toPin":"GND"},{"fromComponent":"Soil moisture","fromPin":"A0","toComponent":"Arduino Uno","toPin":"A0"}]},{"type":"tip","body":"If your soil module has a D0 pin, leave it unconnected. This sketch only reads the analogue A0 output."}]$blocks$::jsonb),
  ('1', 4, 'Attach the OLED on I2C', 'The 0.96" OLED speaks I2C. On an Uno, SDA is A4 and SCL is A5. Those pins stay the same for the rest of the project.', null, $blocks$[{"type":"text","body":"I2C is a two-wire bus: SDA carries data, SCL carries the clock. Many 0.96\" SSD1306 modules sit at address 0x3C. The sketch looks for that address."},{"type":"connections","summary":"OLED I2C on A4/A5","rows":[{"fromComponent":"OLED","fromPin":"VCC","toComponent":"Arduino Uno","toPin":"5V"},{"fromComponent":"OLED","fromPin":"GND","toComponent":"Arduino Uno","toPin":"GND"},{"fromComponent":"OLED","fromPin":"SDA","toComponent":"Arduino Uno","toPin":"A4"},{"fromComponent":"OLED","fromPin":"SCL","toComponent":"Arduino Uno","toPin":"A5"}]},{"type":"warning","body":"Do not swap SDA and SCL. A swapped bus usually leaves the screen black."}]$blocks$::jsonb),
  ('1', 5, 'Understand the plant sketch', 'The sketch reads DHT22 temperature and humidity, analogue soil on A0, analogue light on A1, then prints everything to Serial and the OLED.', null, $blocks$[{"type":"text","body":"dht.readTemperature() and dht.readHumidity() talk to D2. analogRead(A0) is soil moisture (wet soil usually reads lower on most cheap probes). analogRead(A1) is the LDR divider. The OLED block uses Adafruit_SSD1306 at 0x3C."},{"type":"code","language":"Arduino","filename":"plant_monitor.ino","libraries":["DHT sensor library","Adafruit Unified Sensor","Adafruit GFX Library","Adafruit SSD1306"],"code":"#include <Wire.h>\n#include <DHT.h>\n#include <Adafruit_GFX.h>\n#include <Adafruit_SSD1306.h>\n\n#define DHTPIN 2\n#define DHTTYPE DHT22\n#define SOIL_PIN A0\n#define LDR_PIN A1\n#define OLED_WIDTH 128\n#define OLED_HEIGHT 64\n#define OLED_RESET -1\n#define OLED_ADDRESS 0x3C\n\nDHT dht(DHTPIN, DHTTYPE);\nAdafruit_SSD1306 display(OLED_WIDTH, OLED_HEIGHT, &Wire, OLED_RESET);\n\nvoid setup() {\n  Serial.begin(9600);\n  dht.begin();\n\n  if (!display.begin(SSD1306_SWITCHCAPVCC, OLED_ADDRESS)) {\n    Serial.println(\"OLED not found. Check SDA/SCL.\");\n    while (true) {}\n  }\n\n  display.clearDisplay();\n  display.setTextColor(SSD1306_WHITE);\n  display.setTextSize(1);\n  display.setCursor(0, 24);\n  display.println(\"Plant monitor\");\n  display.display();\n  delay(1000);\n}\n\nvoid loop() {\n  float humidity = dht.readHumidity();\n  float temperature = dht.readTemperature();\n  int soil = analogRead(SOIL_PIN);\n  int light = analogRead(LDR_PIN);\n\n  Serial.print(\"Temp C: \");\n  Serial.print(temperature);\n  Serial.print(\"  Hum %: \");\n  Serial.print(humidity);\n  Serial.print(\"  Soil: \");\n  Serial.print(soil);\n  Serial.print(\"  Light: \");\n  Serial.println(light);\n\n  display.clearDisplay();\n  display.setCursor(0, 0);\n  display.println(\"Smart Plant\");\n  display.print(\"Temp: \");\n  display.print(isnan(temperature) ? 0 : temperature, 1);\n  display.println(\" C\");\n  display.print(\"Hum:  \");\n  display.print(isnan(humidity) ? 0 : humidity, 1);\n  display.println(\" %\");\n  display.print(\"Soil: \");\n  display.println(soil);\n  display.print(\"Light:\");\n  display.println(light);\n  display.display();\n\n  delay(2000);\n}"}]$blocks$::jsonb),
  ('1', 6, 'Upload and watch the display', 'Select Arduino Uno, pick the USB port, install the listed libraries, then upload. Open Serial Monitor at 9600 baud as well as watching the OLED.', 'If upload fails, try a data-capable USB cable. Charge-only cables never appear as a port.', $blocks$[{"type":"text","body":"After upload the OLED should show four lines: temperature, humidity, soil, and light. Serial should print the same four values every two seconds."},{"type":"expected","heading":"Expected result","body":"Cover the LDR and A1 should fall. Hold the DHT22 and temperature should rise. Dip the soil probe in water and A0 should change. The OLED updates in step with Serial."}]$blocks$::jsonb),
  ('1', 7, 'Test each sensor', 'Change only one environment at a time so you know which reading belongs to which sensor.', null, $blocks$[{"type":"troubleshooting","items":[{"problem":"OLED stays black","solution":"Confirm VCC/GND, SDA→A4, SCL→A5, and address 0x3C. Power-cycle after a failed init."},{"problem":"DHT22 prints nan","solution":"DATA must be on D2. VCC is 5V. Wait two seconds between reads — the sensor is slow."},{"problem":"Soil reading never moves","solution":"You must use the analogue A0 pin on the module, not D0. Share GND with the Uno."}]},{"type":"tip","body":"Soil probes can corrode if left powered in wet soil for days. For long-term use, take a reading then unplug USB when you are done testing."}]$blocks$::jsonb),
  ('1', 8, 'Read the garden, not just the numbers', 'You now have a local dashboard: soil, climate, and light on one board. Use the numbers to decide when to water or move the plant.', null, $blocks$[{"type":"image","imageKey":"smartPlantMonitor","caption":"Keep the same pin map if you enclose the build later."},{"type":"expected","heading":"What you built","body":"Uno D2 = DHT22 data, A0 = soil analogue, A1 = LDR divider (resistor to GND), OLED on I2C A4/A5. No extra hardware was required."}]$blocks$::jsonb),
  ('4', 0, 'A weather station without extra screens', 'This build uses an ESP32, DHT22, and BMP280 only. Temperature and humidity come from the DHT22. Pressure comes from the BMP280. You will watch the values in the Serial Monitor — there is no OLED in the BOM.', null, $blocks$[{"type":"image","imageKey":"weatherStation","caption":"ESP32 weather station reference."},{"type":"text","body":"ESP32 GPIO is 3.3 V. Power both sensors from 3V3, not 5 V. I2C for the BMP280 uses GPIO 21 (SDA) and GPIO 22 (SCL). The DHT22 data line is GPIO 4."},{"type":"components","items":[{"id":"esp32","name":"ESP32 DevKit","illustrationId":"esp32","owned":false,"quantity":1},{"id":"dht22","name":"DHT22","illustrationId":"dht11","owned":false,"quantity":1},{"id":"bmp280","name":"BMP280","illustrationId":"generic-sensor","owned":false,"quantity":1},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]}]$blocks$::jsonb),
  ('4', 1, 'Prepare the ESP32 and breadboard', 'Seat the ESP32 DevKit so 3V3, GND, GPIO 4, GPIO 21, and GPIO 22 can reach the breadboard rails with jumper wires.', null, $blocks$[{"type":"text","body":"GPIO means general-purpose input/output. Numbered pins on the ESP32 can be digital or, on some pins, analogue. This project uses GPIO 4 as a digital sensor pin and 21/22 as the I2C pair."},{"type":"warning","body":"Do not power the BMP280 from 5 V. It is a 3.3 V part. The ESP32 3V3 pin is the correct supply."},{"type":"components","items":[{"id":"esp32","name":"ESP32 DevKit","illustrationId":"esp32","owned":false,"quantity":1},{"id":"dht22","name":"DHT22","illustrationId":"dht11","owned":false,"quantity":1},{"id":"bmp280","name":"BMP280","illustrationId":"generic-sensor","owned":false,"quantity":1},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]}]$blocks$::jsonb),
  ('4', 2, 'Wire the DHT22', 'The DHT22 reports temperature and humidity on a single data pin. On this ESP32 that pin is GPIO 4.', null, $blocks$[{"type":"wiring","pair":{"leftName":"ESP32","leftId":"esp32","rightName":"DHT22","rightId":"dht11"},"connections":[{"fromComponent":"DHT22","fromPin":"VCC","toComponent":"ESP32","toPin":"3V3"},{"fromComponent":"DHT22","fromPin":"GND","toComponent":"ESP32","toPin":"GND"},{"fromComponent":"DHT22","fromPin":"DATA","toComponent":"ESP32","toPin":"GPIO4"}]},{"type":"text","body":"Use a DHT22 module with an onboard pull-up. This BOM has no spare resistor for a discrete pull-up."}]$blocks$::jsonb),
  ('4', 3, 'Wire the BMP280 on I2C', 'The BMP280 measures pressure (and temperature) over I2C. SDA goes to GPIO 21 and SCL to GPIO 22 for the rest of this guide.', null, $blocks$[{"type":"connections","summary":"BMP280 I2C on GPIO 21/22","rows":[{"fromComponent":"BMP280","fromPin":"VCC","toComponent":"ESP32","toPin":"3V3"},{"fromComponent":"BMP280","fromPin":"GND","toComponent":"ESP32","toPin":"GND"},{"fromComponent":"BMP280","fromPin":"SDA","toComponent":"ESP32","toPin":"GPIO21"},{"fromComponent":"BMP280","fromPin":"SCL","toComponent":"ESP32","toPin":"GPIO22"}]},{"type":"tip","body":"Some BMP280 modules use address 0x76, others 0x77. The sketch tries both."}]$blocks$::jsonb),
  ('4', 4, 'Read the sketch', 'The program starts Serial at 115200, initialises the DHT22 on GPIO 4, then talks to the BMP280 on I2C. Each loop prints temperature, humidity, and pressure in hPa.', null, $blocks$[{"type":"text","body":"Pressure is returned in pascals; dividing by 100 converts to hectopascals (hPa), the usual weather unit. There is no Wi-Fi call and no extra display module — Serial is the output."},{"type":"code","language":"Arduino","filename":"weather_station.ino","libraries":["DHT sensor library","Adafruit Unified Sensor","Adafruit BMP280 Library"],"code":"#include <Wire.h>\n#include <DHT.h>\n#include <Adafruit_Sensor.h>\n#include <Adafruit_BMP280.h>\n\n#define DHTPIN 4\n#define DHTTYPE DHT22\n#define BMP_SDA 21\n#define BMP_SCL 22\n\nDHT dht(DHTPIN, DHTTYPE);\nAdafruit_BMP280 bmp;\n\nvoid setup() {\n  Serial.begin(115200);\n  delay(1000);\n  dht.begin();\n  Wire.begin(BMP_SDA, BMP_SCL);\n\n  if (!bmp.begin(0x76) && !bmp.begin(0x77)) {\n    Serial.println(\"BMP280 not found. Check SDA=21, SCL=22, VCC=3V3.\");\n    while (true) {}\n  }\n\n  bmp.setSampling(\n    Adafruit_BMP280::MODE_NORMAL,\n    Adafruit_BMP280::SAMPLING_X2,\n    Adafruit_BMP280::SAMPLING_X16,\n    Adafruit_BMP280::FILTER_X16,\n    Adafruit_BMP280::STANDBY_MS_500\n  );\n\n  Serial.println(\"Weather station ready\");\n}\n\nvoid loop() {\n  float humidity = dht.readHumidity();\n  float temperature = dht.readTemperature();\n  float pressure = bmp.readPressure() / 100.0F;\n\n  Serial.print(\"Temp C: \");\n  Serial.print(temperature);\n  Serial.print(\"  Hum %: \");\n  Serial.print(humidity);\n  Serial.print(\"  Pressure hPa: \");\n  Serial.println(pressure);\n\n  delay(2000);\n}"}]$blocks$::jsonb),
  ('4', 5, 'Upload to the ESP32', 'In the Arduino IDE choose your ESP32 Dev Module, select the port, install the listed libraries, and upload. Open Serial Monitor at 115200 baud.', null, $blocks$[{"type":"text","body":"Hold the BOOT button if the first upload times out, then retry. After reset you should see “Weather station ready” then repeating weather lines."},{"type":"expected","heading":"Expected result","body":"Temperature and humidity change if you breathe on the DHT22. Pressure is a stable value near local weather (often 980–1030 hPa at low altitude)."}]$blocks$::jsonb),
  ('4', 6, 'Use the readings', 'Compare DHT22 temperature with the BMP280’s idea of temperature if you print bmp.readTemperature() later. For this project, treat DHT22 as climate and BMP280 as pressure.', null, $blocks$[{"type":"troubleshooting","items":[{"problem":"BMP280 not found","solution":"3V3 and GND first, then SDA=21, SCL=22. Try the other I2C address. Do not use 5 V."},{"problem":"DHT22 nan values","solution":"DATA must be GPIO 4. Wait two seconds between reads. Confirm 3V3, not 5 V, on VCC."},{"problem":"Blank Serial","solution":"Set the monitor to 115200 baud. ESP32 logs are easy to miss at 9600."}]}]$blocks$::jsonb),
  ('4', 7, 'Station complete', 'You have a three-value weather station on the ESP32 using only the BOM parts. Pin map: DHT22 DATA = GPIO 4, BMP280 SDA = 21, SCL = 22, all VCC = 3V3.', null, $blocks$[{"type":"image","imageKey":"weatherStation","caption":"Keep 3.3 V power if you move the station to a box."},{"type":"expected","heading":"What you built","body":"ESP32 reads DHT22 humidity/temperature and BMP280 pressure, then prints them over USB Serial. No OLED or cloud module was used."}]$blocks$::jsonb),
  ('8', 0, 'Build a motion alarm', 'A PIR sensor goes HIGH when it sees a moving infrared source. The sketch turns on an LED and an active buzzer on that signal. No extra switch or battery is required — USB power is enough.', null, $blocks$[{"type":"image","imageKey":"motionSensor","caption":"PIR alarm reference."},{"type":"components","items":[{"id":"arduino-uno-r3","name":"Arduino Uno R3","illustrationId":"arduino-uno","owned":false,"quantity":1},{"id":"pir-sensor","name":"PIR motion sensor","illustrationId":"pir-sensor","owned":false,"quantity":1},{"id":"buzzer","name":"Buzzer","illustrationId":"generic-module","owned":false,"quantity":1},{"id":"led","name":"LED","illustrationId":"led","owned":false,"quantity":1},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":1},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]},{"type":"text","body":"Pin map for every later step: PIR OUT → D2, LED anode via resistor → D8, LED cathode → GND, buzzer signal → D9, buzzer GND → GND. PIR and buzzer VCC use 5V."}]$blocks$::jsonb),
  ('8', 1, 'Identify the outputs', 'The LED needs the BOM resistor in series. The catalogue buzzer is an active buzzer: HIGH on the signal pin makes it sound. You do not need tone() for an active buzzer.', null, $blocks$[{"type":"text","body":"LED polarity: the longer lead is the anode (toward D8 through the resistor). The shorter lead, or the flat side of the plastic, is the cathode to GND."},{"type":"components","items":[{"id":"arduino-uno-r3","name":"Arduino Uno R3","illustrationId":"arduino-uno","owned":false,"quantity":1},{"id":"pir-sensor","name":"PIR motion sensor","illustrationId":"pir-sensor","owned":false,"quantity":1},{"id":"buzzer","name":"Buzzer","illustrationId":"generic-module","owned":false,"quantity":1},{"id":"led","name":"LED","illustrationId":"led","owned":false,"quantity":1},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":1},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]}]$blocks$::jsonb),
  ('8', 2, 'Wire the PIR', 'Most PIR modules have VCC, OUT, and GND. OUT is a digital signal the Arduino can read with digitalRead().', null, $blocks$[{"type":"wiring","pair":{"leftName":"Arduino Uno","leftId":"arduino-uno","rightName":"PIR","rightId":"pir-sensor"},"connections":[{"fromComponent":"PIR","fromPin":"VCC","toComponent":"Arduino Uno","toPin":"5V"},{"fromComponent":"PIR","fromPin":"GND","toComponent":"Arduino Uno","toPin":"GND"},{"fromComponent":"PIR","fromPin":"OUT","toComponent":"Arduino Uno","toPin":"D2"}]},{"type":"tip","body":"PIR sensors need about 30 seconds to settle after power-up. The sketch waits that long and prints a message so you do not walk in front of it during warm-up."}]$blocks$::jsonb),
  ('8', 3, 'Wire the LED and buzzer', 'Put the resistor in series with the LED on D8. Connect the active buzzer signal to D9 and its ground to GND.', null, $blocks$[{"type":"connections","summary":"Alarm outputs on D8 and D9","rows":[{"fromComponent":"Resistor","fromPin":"leg 1","toComponent":"Arduino Uno","toPin":"D8"},{"fromComponent":"Resistor","fromPin":"leg 2","toComponent":"LED","toPin":"anode"},{"fromComponent":"LED","fromPin":"cathode","toComponent":"Arduino Uno","toPin":"GND"},{"fromComponent":"Buzzer","fromPin":"VCC / +","toComponent":"Arduino Uno","toPin":"5V"},{"fromComponent":"Buzzer","fromPin":"I/O / S","toComponent":"Arduino Uno","toPin":"D9"},{"fromComponent":"Buzzer","fromPin":"GND","toComponent":"Arduino Uno","toPin":"GND"}]},{"type":"warning","body":"If your buzzer has only two leads, treat the longer or labelled + lead as the side that goes to D9 and the other to GND, and omit a separate 5V connection."}]$blocks$::jsonb),
  ('8', 4, 'Read the alarm sketch', 'After a 30-second warm-up, loop() reads D2. HIGH means motion: D8 and D9 go HIGH together. LOW means idle: both outputs off.', null, $blocks$[{"type":"text","body":"digitalRead returns HIGH or LOW. Driving an active buzzer with digitalWrite is enough — it contains its own oscillator. A 800 ms delay keeps the alarm from chattering on a short PIR pulse."},{"type":"code","language":"Arduino","filename":"motion_alarm.ino","libraries":[],"code":"const int PIR_PIN = 2;\nconst int LED_PIN = 8;\nconst int BUZZER_PIN = 9;\n\nvoid setup() {\n  pinMode(PIR_PIN, INPUT);\n  pinMode(LED_PIN, OUTPUT);\n  pinMode(BUZZER_PIN, OUTPUT);\n  digitalWrite(LED_PIN, LOW);\n  digitalWrite(BUZZER_PIN, LOW);\n  Serial.begin(9600);\n  Serial.println(\"PIR warming up. Stay still for 30 seconds.\");\n  delay(30000);\n  Serial.println(\"Alarm armed.\");\n}\n\nvoid loop() {\n  int motion = digitalRead(PIR_PIN);\n\n  if (motion == HIGH) {\n    digitalWrite(LED_PIN, HIGH);\n    digitalWrite(BUZZER_PIN, HIGH);\n    Serial.println(\"Motion detected\");\n    delay(800);\n  } else {\n    digitalWrite(LED_PIN, LOW);\n    digitalWrite(BUZZER_PIN, LOW);\n  }\n}"}]$blocks$::jsonb),
  ('8', 5, 'Upload and arm the alarm', 'Board: Arduino Uno. Serial Monitor at 9600 baud. Stay out of the PIR’s view until it prints “Alarm armed.”', null, $blocks$[{"type":"expected","heading":"Expected result","body":"Walk in front of the PIR: the LED lights and the buzzer sounds, and Serial prints “Motion detected”. Step away and both outputs should go quiet."},{"type":"tip","body":"Aim the PIR away from HVAC vents. Fast temperature changes can look like motion to a PIR."}]$blocks$::jsonb),
  ('8', 6, 'Tune the detection', 'If the alarm never fires, check D2 with a Serial print of digitalRead. If it always fires, move the PIR or wait for a full warm-up.', null, $blocks$[{"type":"troubleshooting","items":[{"problem":"LED never lights","solution":"Confirm anode→resistor→D8 and cathode→GND. Swap the LED if you still see nothing — polarity may be reversed."},{"problem":"Buzzer silent","solution":"Active buzzers need DC HIGH on the signal pin. Confirm D9 and GND. A two-pin buzzer goes D9 and GND only."},{"problem":"PIR always HIGH","solution":"Finish the 30 s warm-up. Check OUT is on D2, not a 3.3 V logic pin on a 5 V module without sharing GND."}]}]$blocks$::jsonb),
  ('8', 7, 'Alarm complete', 'You have a USB-powered motion alarm: PIR on D2, LED on D8, buzzer on D9. No extra switch or battery was added.', null, $blocks$[{"type":"image","imageKey":"motionSensor","caption":"Keep the same GPIO map if you mount the PIR on a box."}]$blocks$::jsonb),
  ('11', 0, 'Your first Arduino circuit', 'You will blink the BOM LED from Arduino pin D9 through the BOM resistor. This is the classic first electronics build: polarity, current limiting, breadboard rows, then code.', null, $blocks$[{"type":"image","imageKey":"blinkLed","caption":"Blinking LED starter reference."},{"type":"components","items":[{"id":"arduino-uno-r3","name":"Arduino Uno R3","illustrationId":"arduino-uno","owned":false,"quantity":1},{"id":"led","name":"LED","illustrationId":"led","owned":false,"quantity":1},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":1},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]},{"type":"text","body":"Pin D9 is a digital output. HIGH is about 5 V on an Uno. An LED on 5 V without a resistor can draw enough current to damage the LED or the pin. The resistor limits that current."}]$blocks$::jsonb),
  ('11', 1, 'Find the LED’s anode and cathode', 'The longer LED lead is the anode (positive). The shorter lead, and the flat edge on the plastic lens, is the cathode (negative).', null, $blocks$[{"type":"text","body":"Current through an LED only flows anode → cathode. If you insert it backwards it will not light, but the resistor still protects the pin."},{"type":"components","items":[{"id":"led","name":"LED","illustrationId":"led","owned":false,"quantity":1},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":1}]},{"type":"tip","body":"The resistor has no polarity. Either orientation is correct."}]$blocks$::jsonb),
  ('11', 2, 'Place parts on the breadboard', 'A breadboard’s centre gap splits the two sides. Holes in one row (a numbered row on one side of the gap) are connected. Use that to join the resistor and LED without soldering.', null, $blocks$[{"type":"text","body":"Put the LED across two rows. Put one resistor lead in the same row as the LED anode. The other resistor lead gets a jumper toward D9. The LED cathode row gets a jumper toward GND."},{"type":"warning","body":"Do not let the LED anode and cathode share a row. That shorts the LED."}]$blocks$::jsonb),
  ('11', 3, 'Wire D9 and GND', 'One jumper from D9 to the free resistor lead. One jumper from the LED cathode to a GND pin on the Uno. Keep this pin map for the sketch.', null, $blocks$[{"type":"wiring","pair":{"leftName":"Arduino Uno","leftId":"arduino-uno","rightName":"LED","rightId":"led"},"connections":[{"fromComponent":"Arduino Uno","fromPin":"D9","toComponent":"Resistor","toPin":"leg 1"},{"fromComponent":"Resistor","fromPin":"leg 2","toComponent":"LED","toPin":"anode"},{"fromComponent":"LED","fromPin":"cathode","toComponent":"Arduino Uno","toPin":"GND"}]},{"type":"text","body":"Current path: D9 → resistor → LED anode → LED cathode → GND. That is the whole circuit."}]$blocks$::jsonb),
  ('11', 4, 'Understand blink timing', 'pinMode(9, OUTPUT) makes D9 a GPIO output. digitalWrite HIGH lights the LED. delay(1000) waits 1000 milliseconds. LOW turns it off. The loop repeats forever.', null, $blocks$[{"type":"code","language":"Arduino","filename":"blink_led.ino","libraries":[],"code":"const int LED_PIN = 9;\nconst int ON_MS = 1000;\nconst int OFF_MS = 1000;\n\nvoid setup() {\n  pinMode(LED_PIN, OUTPUT);\n}\n\nvoid loop() {\n  digitalWrite(LED_PIN, HIGH);\n  delay(ON_MS);\n  digitalWrite(LED_PIN, LOW);\n  delay(OFF_MS);\n}"},{"type":"text","body":"ON_MS and OFF_MS are both 1000, so the LED spends one second on and one second off. Changing only those two numbers is the experiment in the last step."}]$blocks$::jsonb),
  ('11', 5, 'Upload the sketch', 'Select Arduino Uno and the correct port, paste the sketch, and click Upload. You do not need extra libraries.', null, $blocks$[{"type":"expected","heading":"Expected result","body":"The BOM LED on D9 blinks once per second. The Uno’s tiny onboard LED on D13 may stay off — that is expected, because this sketch drives D9."},{"type":"troubleshooting","items":[{"problem":"Nothing blinks","solution":"Check anode vs cathode, resistor in series, D9 (not D13), and GND. Reverse the LED if needed."},{"problem":"Upload error","solution":"Choose the Uno board and the COM/cu.usb port. Use a data USB cable."}]}]$blocks$::jsonb),
  ('11', 6, 'Experiment with the delays', 'Change ON_MS to 100 and OFF_MS to 100 for a fast blink, or 2000/2000 for a slow one. Upload again. You are editing time, not hardware.', null, $blocks$[{"type":"text","body":"delay() pauses the whole program. That is fine for a blink. Later projects will read sensors between delays so the board can still react."},{"type":"expected","heading":"What you built","body":"D9 → resistor → LED anode, cathode → GND. Blink timing lives in ON_MS and OFF_MS."}]$blocks$::jsonb),
  ('12', 0, 'Three lights, three pins', 'A traffic light is three independent LED circuits. Each LED gets its own resistor from the BOM (three LEDs, three resistors). The Arduino turns them on in a timed sequence.', null, $blocks$[{"type":"image","imageKey":"trafficLight","caption":"Traffic light simulator reference."},{"type":"components","items":[{"id":"arduino-uno-r3","name":"Arduino Uno R3","illustrationId":"arduino-uno","owned":false,"quantity":1},{"id":"led","name":"LED","illustrationId":"led","owned":false,"quantity":3},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":3},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]},{"type":"text","body":"Pin map: red = D8, yellow = D9, green = D10. Each cathode goes to GND. Never share one resistor across all three LEDs — the BOM gives you one resistor per LED so each colour gets proper current limiting."}]$blocks$::jsonb),
  ('12', 1, 'Polarity for every LED', 'Long lead = anode toward the resistor and Arduino pin. Short lead / flat side = cathode to GND. Repeat that for red, yellow, and green.', null, $blocks$[{"type":"text","body":"If one colour never lights, that LED is probably reversed. The other two can still work because they are separate circuits."},{"type":"tip","body":"If your LEDs are all the same colour, assign them left-to-right as red, yellow, green so the sequence is still readable."}]$blocks$::jsonb),
  ('12', 2, 'Breadboard the three branches', 'Give each LED its own pair of rows. Series resistor on the anode side. Do not bridge the three anodes together.', null, $blocks$[{"type":"text","body":"Think of three copies of the blink circuit, each with its own GPIO. GND can be a shared rail — that is still one ground, not extra hardware."}]$blocks$::jsonb),
  ('12', 3, 'Wire D8, D9, and D10', 'Red resistor to D8, yellow resistor to D9, green resistor to D10. All cathodes to Uno GND. This map is the same in the sketch.', null, $blocks$[{"type":"connections","summary":"One resistor per LED","rows":[{"fromComponent":"Arduino Uno","fromPin":"D8","toComponent":"Red resistor","toPin":"leg 1"},{"fromComponent":"Red resistor","fromPin":"leg 2","toComponent":"Red LED","toPin":"anode"},{"fromComponent":"Red LED","fromPin":"cathode","toComponent":"Arduino Uno","toPin":"GND"},{"fromComponent":"Arduino Uno","fromPin":"D9","toComponent":"Yellow resistor","toPin":"leg 1"},{"fromComponent":"Yellow resistor","fromPin":"leg 2","toComponent":"Yellow LED","toPin":"anode"},{"fromComponent":"Yellow LED","fromPin":"cathode","toComponent":"Arduino Uno","toPin":"GND"},{"fromComponent":"Arduino Uno","fromPin":"D10","toComponent":"Green resistor","toPin":"leg 1"},{"fromComponent":"Green resistor","fromPin":"leg 2","toComponent":"Green LED","toPin":"anode"},{"fromComponent":"Green LED","fromPin":"cathode","toComponent":"Arduino Uno","toPin":"GND"}]}]$blocks$::jsonb),
  ('12', 4, 'Program the sequence', 'allOff() clears every pin. The loop shows red, then yellow, then green, then yellow again — a simple two-way light. Delays are in milliseconds.', null, $blocks$[{"type":"text","body":"Only one colour is HIGH at a time because allOff() runs before each colour. That is safer than stacking HIGH writes and forgetting a LOW."},{"type":"code","language":"Arduino","filename":"traffic_light.ino","libraries":[],"code":"const int RED_PIN = 8;\nconst int YELLOW_PIN = 9;\nconst int GREEN_PIN = 10;\n\nvoid allOff() {\n  digitalWrite(RED_PIN, LOW);\n  digitalWrite(YELLOW_PIN, LOW);\n  digitalWrite(GREEN_PIN, LOW);\n}\n\nvoid setup() {\n  pinMode(RED_PIN, OUTPUT);\n  pinMode(YELLOW_PIN, OUTPUT);\n  pinMode(GREEN_PIN, OUTPUT);\n  allOff();\n}\n\nvoid loop() {\n  allOff();\n  digitalWrite(RED_PIN, HIGH);\n  delay(4000);\n\n  allOff();\n  digitalWrite(YELLOW_PIN, HIGH);\n  delay(1000);\n\n  allOff();\n  digitalWrite(GREEN_PIN, HIGH);\n  delay(4000);\n\n  allOff();\n  digitalWrite(YELLOW_PIN, HIGH);\n  delay(1000);\n}"}]$blocks$::jsonb),
  ('12', 5, 'Upload and watch the cycle', 'Arduino Uno, no extra libraries. After upload you should see red (4 s), yellow (1 s), green (4 s), yellow (1 s), repeat.', null, $blocks$[{"type":"expected","heading":"Expected result","body":"The three LEDs take turns. No two colours stay on together. Timing should feel like a slow traffic light, not a blink."}]$blocks$::jsonb),
  ('12', 6, 'Change the timing on purpose', 'Edit the delay() values to make green longer or yellow shorter. Upload again. You are changing software state duration, not the wiring.', null, $blocks$[{"type":"troubleshooting","items":[{"problem":"One colour missing","solution":"Check that LED’s anode resistor pin (D8/D9/D10) and cathode GND. Reverse that LED if needed."},{"problem":"Two colours at once","solution":"Confirm allOff() is called before each colour. Confirm no shared anode row on the breadboard."}]}]$blocks$::jsonb),
  ('12', 7, 'Sequence complete', 'Red D8, yellow D9, green D10, one resistor each, shared GND. That is the whole traffic light.', null, $blocks$[{"type":"image","imageKey":"trafficLight","caption":"Keep D8/D9/D10 if you mount the LEDs in a card model."}]$blocks$::jsonb),
  ('14', 0, 'A lamp that follows the room', 'An LDR changes resistance with light. In a voltage divider with one BOM resistor, that becomes a voltage the Arduino can analogRead(). The second BOM resistor current-limits the LED on D9. No transistor, MOSFET, or extra supply is required — the GPIO can drive this single LED.', null, $blocks$[{"type":"image","imageKey":"nightLamp","caption":"Light-activated night lamp reference."},{"type":"components","items":[{"id":"arduino-uno-r3","name":"Arduino Uno R3","illustrationId":"arduino-uno","owned":false,"quantity":1},{"id":"ldr","name":"LDR","illustrationId":"generic-sensor","owned":false,"quantity":1},{"id":"led","name":"LED","illustrationId":"led","owned":false,"quantity":1},{"id":"resistor","name":"Resistor","illustrationId":"resistor","owned":false,"quantity":2},{"id":"breadboard","name":"Breadboard","illustrationId":"breadboard","owned":false,"quantity":1},{"id":"jumper-wires","name":"Jumper wires","illustrationId":"jumper-wires","owned":false,"quantity":1}]}]$blocks$::jsonb),
  ('14', 1, 'Voltage dividers in one minute', 'Two resistances in series share the 5 V rail. The middle node is a voltage between 0 V and 5 V. analogRead maps that to 0–1023 on an Uno.', null, $blocks$[{"type":"text","body":"Here the LDR is from 5V to A0 and one resistor is from A0 to GND. In bright light the LDR resistance is low, so A0 sits closer to 5 V (a high reading). In the dark the LDR resistance is high, so A0 drops (a low reading). The sketch turns the lamp on when the reading is below DARK_THRESHOLD."}]$blocks$::jsonb),
  ('14', 2, 'Build the LDR divider', 'Use one of the two BOM resistors on the A0-to-GND leg. Leave the other resistor for the LED.', null, $blocks$[{"type":"connections","summary":"LDR divider on A0","rows":[{"fromComponent":"LDR","fromPin":"leg 1","toComponent":"Arduino Uno","toPin":"5V"},{"fromComponent":"LDR","fromPin":"leg 2","toComponent":"Arduino Uno","toPin":"A0"},{"fromComponent":"Resistor 1","fromPin":"leg 1","toComponent":"Arduino Uno","toPin":"A0"},{"fromComponent":"Resistor 1","fromPin":"leg 2","toComponent":"Arduino Uno","toPin":"GND"}]},{"type":"tip","body":"The LDR also has no polarity. Either orientation is fine."}]$blocks$::jsonb),
  ('14', 3, 'Wire the LED on D9', 'Same rule as the blink project: D9 → resistor 2 → LED anode, cathode → GND. The LED is the “lamp”.', null, $blocks$[{"type":"wiring","pair":{"leftName":"Arduino Uno","leftId":"arduino-uno","rightName":"LED","rightId":"led"},"connections":[{"fromComponent":"Arduino Uno","fromPin":"D9","toComponent":"Resistor 2","toPin":"leg 1"},{"fromComponent":"Resistor 2","fromPin":"leg 2","toComponent":"LED","toPin":"anode"},{"fromComponent":"LED","fromPin":"cathode","toComponent":"Arduino Uno","toPin":"GND"}]},{"type":"warning","body":"Do not drive the LED from A0. A0 is an input that only senses the divider. D9 is the output that powers the LED."}]$blocks$::jsonb),
  ('14', 4, 'Threshold logic', 'analogRead(A0) is compared with DARK_THRESHOLD (500 to start). Below the threshold means dark → LED HIGH. Above means bright → LED LOW. Serial prints both the number and ON/OFF so you can pick a better threshold.', null, $blocks$[{"type":"code","language":"Arduino","filename":"night_lamp.ino","libraries":[],"code":"const int LDR_PIN = A0;\nconst int LED_PIN = 9;\nconst int DARK_THRESHOLD = 500;\n\nvoid setup() {\n  pinMode(LED_PIN, OUTPUT);\n  Serial.begin(9600);\n}\n\nvoid loop() {\n  int lightLevel = analogRead(LDR_PIN);\n  bool isDark = lightLevel < DARK_THRESHOLD;\n\n  digitalWrite(LED_PIN, isDark ? HIGH : LOW);\n\n  Serial.print(\"Light: \");\n  Serial.print(lightLevel);\n  Serial.print(\"  Lamp: \");\n  Serial.println(isDark ? \"ON\" : \"OFF\");\n  delay(200);\n}"},{"type":"text","body":"500 is a starting point, not a physical constant. Your resistor value and room lighting will differ. Use Serial to choose a number between the bright and dark readings you actually see."}]$blocks$::jsonb),
  ('14', 5, 'Upload and cover the LDR', 'Arduino Uno, 9600 baud Serial. Cover the LDR with your hand: the reading should fall and the LED should light. Shine a lamp on it: the reading should rise and the LED should go out.', null, $blocks$[{"type":"expected","heading":"Expected result","body":"Serial shows a high Light value in a bright room and a lower value in shadow. The lamp line tracks that with ON when dark."}]$blocks$::jsonb),
  ('14', 6, 'Pick your own threshold', 'Note a bright reading (for example 800) and a dark reading (for example 200). Set DARK_THRESHOLD halfway between them, upload, and test again.', null, $blocks$[{"type":"troubleshooting","items":[{"problem":"Light value never changes","solution":"Confirm the divider: LDR to 5V and A0, resistor 1 to A0 and GND. analogRead must use A0."},{"problem":"LED always on or always off","solution":"Print lightLevel. Move DARK_THRESHOLD between your bright and dark numbers. Check LED polarity on D9."},{"problem":"LED is dim","solution":"That is the current-limiting resistor doing its job. Do not bypass it."}]}]$blocks$::jsonb),
  ('14', 7, 'Night lamp complete', 'A0 reads the LDR divider (resistor 1). D9 drives the LED (resistor 2). Threshold logic in software decides when the room is dark.', null, $blocks$[{"type":"image","imageKey":"nightLamp","caption":"Same A0/D9 map if you place the LDR in a window."}]$blocks$::jsonb)
) as v(slug, sort_order, title, description, tip, blocks)
join public.projects p on p.slug = v.slug;
